<a href="https://colab.research.google.com/github/jyothijoo197-ui/AI-POWERED-DEBT-RELIEF-AND-FINANCIAL-RECOVERY-PLATFORM-/blob/main/Data_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Variables

In [1]:
# Variable: Variable is like a container that holds information
# We can use it to Store name, number, float... even something more complex

In [3]:
name = "Jyothi Kiran"
# Which stores the word john as a string in the variable called name

In [4]:
print(name)

Jyothi Kiran


In [5]:
type(name)

str

In [6]:
age = 20
# The number 25 is stored as an integer

In [7]:
print(age)

20


In [8]:
type(age)

int

In [10]:
height = 7.3
# Python understands this as a decimal or float

In [11]:
print(height)

7.3


In [12]:
type(height)

float

Lists

In [13]:
# Store group of items: List

In [14]:
person = ["Jyothi Kiran", 20, 7.3]

In [15]:
person[0]

'Jyothi Kiran'

In [16]:
person[1]

20

In [17]:
person[2]

7.3

In [18]:
# List are also mutuable or changeable that means we can update any value from the list using the indexing method.

In [23]:
person[0] = "JK"

In [24]:
person

['JK', 20, 7.3]

In [25]:
# Lists are also flexible that is we can add new items to them or remove existing one using simple command like .append() or .remove()

In [26]:
person.append("Swimming")

In [27]:
person

['JK', 20, 7.3, 'Swimming']

In [29]:
person.remove(20)

In [30]:
person

['JK', 7.3, 'Swimming']

Tuple

In [31]:
# Store values but in immutable manner : Tuple
# A tuple is very similar to the list but once it's created it cannot be modified

In [32]:
coordinates = (10,20)

In [33]:
# For instance if we write comma seperated values inside paranthesis we created the tuple two values and this means exactly same

In [34]:
print(coordinates)

(10, 20)


In [35]:
type(coordinates)

tuple

In [36]:
coordinates[0]

10

In [37]:
# If we try to change a particular value python will rise an error.
# Tuples are great for storing data but shouldn't change like a fixed locations, phone numbers or dimensions.

In [38]:
coordinates[0] = 100

TypeError: 'tuple' object does not support item assignment

Dictionaries

In [ ]:
# Dictionaries:
# A dictionary in python stores data in pairs, a key and a value.
# Just like a real life dictionary where each word has a meaning.
# For example, if we right this piece of code, then name, age and height or the keys and their respective values.
# We can get the value of anything simply by using it's name like person and inside the square brackets the key.
# We can also update the values and add new pairs any time we like.

In [40]:
p = {"name" : "Jyothi Kiran", "age" : 20, "height" : 7.3}

In [41]:
print(p)

{'name': 'Jyothi Kiran', 'age': 20, 'height': 7.3}


In [42]:
type(p)

dict

In [43]:
p["name"]

'Jyothi Kiran'

In [44]:
p["name"] = "Jonny"

In [45]:
p

{'name': 'Jonny', 'age': 20, 'height': 7.3}

In [46]:
p["sport"] = "swimming"

In [47]:
p

{'name': 'Jonny', 'age': 20, 'height': 7.3, 'sport': 'swimming'}

Loops

In [48]:
# Loops : Loops help us to repeat a task multiple times without having to write the same line of code again and again
# -> for: known iterations
# -> while: until a condition is met

In [49]:
# for : A for loop is useful when we know exactly how many times we want to repeat something

In [50]:
# sum = 1 + 2+ 3+ 4....

In [51]:
sum = 0
for i in range(1, 11):
  sum += i

print(sum)

55


In [52]:
# while: A while loop is used when we want to keep repeating something until a certain condition is no longer true

In [63]:
sum = 0
i = 0
while(i < 6):
  sum += i
  i += 1

print(sum)

15


Functions

In [64]:
# Functions:
# -> Avoids code repetition
# -> Reuse the code any number of times
# -> Simply need to call the function.

In [65]:
# Adding 2 numbers:

def add_numbers(a,b):
  return a+b

In [66]:
add_numbers(10,20)

30

In [67]:
add_numbers(51343,349875)

401218

Numpy - Numerical Python

In [68]:
import numpy as np

In [69]:
sales = np.array([[1200, 1500, 1700], [1000, 1100, 1300]])  # -> 2 dimensional data

In [70]:
# row1 -> north
# row2 -> south
# columns -> months(Jan, Feb, March)

In [71]:
# North sales:
sales[0]

array([1200, 1500, 1700])

In [72]:
# Sales in South in the month of may:
sales[1][2]

np.int64(1300)

In [73]:
# Calculate total sales (both regions, all 3 months):

np.sum(sales)

np.int64(7800)

In [74]:
# Average sales of both the regions:
np.mean(sales, axis = 1)

array([1466.66666667, 1133.33333333])

In [75]:
# Average sales of each month:
np.mean(sales, axis = 0)

array([1100., 1300., 1500.])

In [76]:
# Reshaping data:
data = np.arange(12)

In [77]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
# structuring data:
data2 = np.reshape(data, (4,3))
data2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
sales = np.array([1000, 0, 1200, 0, 15000])
sales

array([ 1000,     0,  1200,     0, 15000])

In [80]:
np.mean(sales)

np.float64(3440.0)

In [81]:
filtered_sales = sales[sales > 0]
filtered_sales

array([ 1000,  1200, 15000])

In [82]:
np.mean(filtered_sales)

np.float64(5733.333333333333)

In [83]:
# Generating random numbers between 100 and 1000:

np.random.randint(100, 1000, 10)

array([781, 356, 783, 102, 467, 582, 206, 193, 666, 975])